# Site settings
title: Patrick Martin
email: pcmart03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal portfolio page. It is built using Jekyll, Sass, and Skeleton.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pcmart03.github.io/" # the base hostname & protocol for your site
twitter_username: pcmart03
github_username:  pcmart03
github_profile: "https://github.com/pcmart03"
linkedin_profile: "https://www.linkedin.com/in/pcmart03"

# Build settings
markdown: kramdown
